#!/bin/bash

INC="./inc"
CFLAGS="-fstrength-reduce -fomit-frame-pointer -finline-functions -nostdinc -fno-builtin -O -Wextra -Wall -m32"
LDFLAGS="-m elf_i386"
NASMFLAGS="-f elf"
LOG="build.log"

rm ${LOG} &> /dev/null

echo "Remove old kernel"
rm kernel.bin &>> ${LOG}

nasm ${NASMFLAGS} kernel_start.asm -o ks.o &>> ${LOG} && \
    gcc ${CFLAGS} -c kernel.c -o kernel.o -I${INC} &>> ${LOG} && \
    gcc ${CFLAGS} -c system.c -o system.o -I${INC} &>> ${LOG} && \
    ld  ${LDFLAGS} -T link.ld -o kernel.bin ks.o kernel.o system.o &>> ${LOG} || \
    echo "Failed build kernel" && exit 0

echo "Remove object files"
rm *.o &>> ${LOG}
exit 1;
